Feature/mainpage
winteryy/nbc_contact pull request #4
Opened 2024-04-23 07:49 UTC by kory0115

메인 페이지

2024-04-23 07:52 UTC, winteryy requested changes
일단 러프하게 합칠거라 자동생성 된 거만 지우면 될 것 같습니다.

2024-04-25 01:34 UTC, Jeong2234 approved these changes

2024-04-25 02:00 UTC, winteryy requested changes
나머지 부분은 수정 이후에 다시 볼게요

2024-04-25 02:00 UTC, winteryy commented on app/src/main/java/com/nbcteam5/nbccontact/MainActivity.kt
> +            })
화면 공유해서 설명 드린것처럼 각 프래그먼트 메소드 생성 후 이용하게 바꾸면 좋겠습니다

2024-04-25 06:17 UTC, winteryy approved these changes
리뷰 읽어보시고, 필요하시면 수정 후에 바로 병합하시면 될 것 같습니다.
나머지는 병합 후에 확인해봐야 할 것 같아요!

2024-04-25 06:17 UTC, winteryy commented on app/src/main/java/com/nbcteam5/nbccontact/MainActivity.kt
> +    }
의도대로 잘 변경해주신 것 같습니다!!👍

2024-04-25 06:17 UTC, winteryy commented on app/src/main/java/com/nbcteam5/nbccontact/MainActivity.kt
> +    }
여기는 병합 후에, 한번 더 확인해보겠습니다

2024-04-25 06:17 UTC, winteryy commented on app/src/main/java/com/nbcteam5/nbccontact/MainFragment.kt
> +        initViews(binding)
`binding`을 여기서 또 만든 이유는 뭔가요??
이미 인자로 받고 있는 `view`는 `FragmentMainBinding`를 `inflate`한 것인데, 이렇게 구성하면 어떤 이점이 있나요

2024-04-25 06:17 UTC, winteryy commented on app/src/main/java/com/nbcteam5/nbccontact/MainFragment.kt
> +
위에서도 언급했지만, 만약 별다른 이유가 없다면 이렇게 불필요한 인자를 넘기는 것 보다는
이미 전역으로 선언해둔 binding을 사용하는 것이 유리할 것 같습니다!

2024-04-25 06:27 UTC, kory0115 commented on app/src/main/java/com/nbcteam5/nbccontact/MainFragment.kt
> +        initViews(binding)
수정했습니다.

2024-04-25 06:27 UTC, merged